### Config
# >- new line

title: "Ethan Nguyen"
name: "Ethan Nguyen"
email: "ethannguyen@utexas.edu"
url: ""
repository: "ethanpnguyen/ethanpnguyen.github.io"
# baseurl: "" # the subpath of your site, e.g. /blog

# Author Profile
author:
  name   : "Ethan Nguyen"
  # avatar : ""
  bio    : "Mechanical Engineering<br>@ UT Austin<br>"
  location: "Austin, TX"
  github : ethanpnguyen
  linkedin: ethanpnguyen
  email  : ethannguyen@utexas.edu

# Build settings
markdown: kramdown
theme: "minimal-mistakes-jekyll"
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
