### Config
# >- new line

title: ' '
title_separator: " "
mastheadtitle: "ethanpnguyen.github.io"
# name: "Ethan Nguyen's Portfolio"
# logo: "assets/favicon/android-chrome-384x384.png"
email: "ethannguyen@utexas.edu"
url: ""
repository: "ethanpnguyen/ethanpnguyen.github.io"
# baseurl: "" # the subpath of your site, e.g. /blog

# Author Profile
author:
  name   : "Ethan Nguyen"
  avatar : "/assets/images/headshot.jpeg"
  bio    : "Mechanical Engineering<br>Senior @ UT Austin<br>"
  location: "Austin, TX"
  github : ethanpnguyen
  linkedin: ethanpnguyen
  email  : ethannguyen@utexas.edu

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # "air"contrast", "aqua", "dirt", "sunrise", "dark", "default", "neon", "plum", "mint"

plugins:
  - jekyll-feed
  - jekyll-include-cache

include: ["_pages"]

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      show_date: true
  # _now_archive
  - scope:
      path: ""
      type: now
    values:
      layout: single
      author_profile: false
      share: true
      show_date: false
      
# Collections
collections:
  now:
    output: true
    permalink: /:collection/:path/

category_archive:
  type: liquid
  path: /categories/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-8PXH7WDM40"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
